import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MOA Collection",
  description: "Generated by create next app",
  // icons:{
  //   icon:'http://www.w3.org/2000/svg',
  //   apple:'http://www.w3.org/2000/svg'
  // }

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <link rel="icon" href="/public/icons8-internet-16.png" />

      <body className={inter.className}>{children}</body>
    </html>
  );
}
